name: pre-commit
on:
  pull_request:
    branches:
    - main
jobs:
  pre-commit-ci:
    name: Lint changed backend files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +${{github.base_ref}}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --from-ref origin/${{github.base_ref}} --to-ref HEAD
